import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.assets': 'Assets',
    'nav.orders': 'Orders',
    'nav.integration': 'Integration',
    'nav.withdraw': 'Withdraw',
    'nav.settings': 'Settings',
    'nav.signout': 'Sign Out',
    'nav.merchantPortal': 'Merchant Portal v2.1',

    // Dashboard
    'dashboard.welcome': 'Welcome back, Merchant. Here\'s your financial overview.',
    'dashboard.revenue': 'Total Revenue',
    'dashboard.activeOrders': 'Active Orders',
    'dashboard.pendingPayouts': 'Pending Payouts',
    'dashboard.accountStatus': 'Account Status',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.revenueOverview': 'Revenue Overview',
    'dashboard.completeProfile': 'Complete your profile',
    'dashboard.completeProfileDesc': 'Add your business entity details to enable automatic invoicing features.',
    'dashboard.goToSettings': 'Go to Settings',
    'dashboard.fromLastMonth': 'from last month',
    'dashboard.sinceLastHour': 'since last hour',
    'dashboard.scheduledTonight': 'Scheduled for tonight',
    'dashboard.transactions': 'transactions',
    'dashboard.transactionHistory': 'Transaction History',

    // Actions
    'action.createInvoice': 'Create Invoice',
    'action.withdraw': 'Withdraw',
    'action.apiKeys': 'API Keys',
    'action.settings': 'Settings',
    'action.copy': 'Copy',
    'action.copied': 'Copied',
    'action.view': 'View',
    'action.download': 'Download',
    'action.filter': 'Filter',
    'action.export': 'Export',
    'action.search': 'Search',
    'action.save': 'Save Changes',
    'action.cancel': 'Cancel',
    'action.generate': 'Generate',
    'action.regenerate': 'Regenerate',
    'action.delete': 'Delete',
    'action.edit': 'Edit',
    'action.verify': 'Verify Now',
    'action.continue': 'Continue',

    // Status
    'status.active': 'Active',
    'status.verified': 'Level 2 Verified',
    'status.kybVerified': 'KYB Verified',
    'status.systemActive': 'System Active',
    'status.completed': 'Completed',
    'status.pending': 'Pending',
    'status.processing': 'Processing',
    'status.failed': 'Failed',
    'status.cancelled': 'Cancelled',
    'status.refunded': 'Refunded',

    // Assets
    'assets.title': 'Assets Management',
    'assets.subtitle': 'Monitor your multi-chain balances and sweeping status.',
    'assets.totalBalance': 'Total Balance',
    'assets.swept': 'Swept to Cold Wallet',
    'assets.unswept': 'Unswept (Hot Wallet)',
    'assets.autoSweep': 'Auto-Sweep',
    'assets.on': 'ON',
    'assets.off': 'OFF',
    'assets.asset': 'Asset',
    'assets.chain': 'Chain',
    'assets.balance': 'Balance',
    'assets.value': 'Value (USD)',
    'assets.status': 'Status',
    'assets.action': 'Action',
    'assets.sweepNow': 'Sweep Now',
    'assets.overview': 'Overview',
    'assets.sweepStrategy': 'Sweep Strategy',
    'assets.addressManagement': 'Address Management',
    'assets.nextBatch': 'Next batch',
    'assets.lastSweep': 'Last sweep',
    'assets.hoursAgo': 'hours ago',
    'assets.addressesProcessed': 'addresses processed',
    'assets.autoSweepConfig': 'Auto-Sweep Configuration',
    'assets.autoSweepConfigDesc': 'Configure automatic sweeping of funds to your cold wallet',
    'assets.sweepThreshold': 'Sweep Threshold',
    'assets.sweepThresholdDesc': 'Minimum balance to trigger sweep',
    'assets.schedule': 'Schedule',
    'assets.everyHour': 'Every Hour',
    'assets.every4Hours': 'Every 4 Hours',
    'assets.dailyAt2AM': 'Daily at 2 AM UTC',
    'assets.manualOnly': 'Manual Only',
    'assets.scheduleDesc': 'When to automatically sweep funds',
    'assets.targetSweepAddress': 'Target Sweep Address',
    'assets.targetSweepAddressDesc': 'Cold wallet address where funds will be sent',
    'assets.gasPriceStrategy': 'Gas Price Strategy',
    'assets.slow': 'Slow (Low Cost)',
    'assets.standard': 'Standard',
    'assets.fast': 'Fast (High Cost)',
    'assets.testSweep': 'Test Sweep',
    'assets.recentSweepHistory': 'Recent Sweep History',
    'assets.time': 'Time',
    'assets.addresses': 'Addresses',
    'assets.manualSweep': 'Manual Sweep',
    'assets.manualSweepDesc': 'Trigger an immediate sweep of all eligible addresses',
    'assets.startSweepNow': 'Start Sweep Now',
    'assets.sweepStatistics': 'Sweep Statistics',
    'assets.totalSwept30d': 'Total Swept (30d)',
    'assets.gasFeesSpent': 'Gas Fees Spent',
    'assets.depositAddresses': 'Deposit Addresses',
    'assets.depositAddressesDesc': 'Manage and monitor your deposit addresses',
    'assets.allAssets': 'All Assets',
    'assets.generateAddress': 'Generate Address',
    'assets.label': 'Label',
    'assets.address': 'Address',
    'assets.transactions': 'Transactions',
    'assets.lastActivity': 'Last Activity',
    'status.idle': 'Idle',

    // Orders
    'orders.title': 'Order History',
    'orders.subtitle': 'View and manage your transaction records.',
    'orders.orderId': 'Order ID',
    'orders.customer': 'Customer',
    'orders.amount': 'Amount',
    'orders.date': 'Date',
    'orders.paymentMethod': 'Payment Method',
    'orders.invoice': 'Invoice',
    'orders.allStatus': 'All Status',
    'orders.allTypes': 'All Types',
    'orders.type': 'Type',
    'orders.payment': 'Payment',
    'orders.payout': 'Payout',
    'orders.onExplorer': 'on Explorer',
    'orders.csv': 'CSV',
    'orders.createdOn': 'Created on',
    'orders.totalAmount': 'Total Amount',
    'orders.fiatEquivalent': 'Fiat Equivalent',
    'orders.timeRemaining': 'Time Remaining',
    'orders.paymentDetails': 'Payment Details',
    'orders.network': 'Network',
    'orders.destination': 'Destination Address',
    'orders.txHash': 'Transaction Hash',
    'orders.blockHeight': 'Block Height',
    'orders.confirmations': 'Confirmations',
    'orders.timeline': 'Payment Timeline',
    'orders.orderCreated': 'Order Created',
    'orders.paymentDetected': 'Payment Detected',
    'orders.confirming': 'Confirming',
    'orders.inProgress': 'In Progress',
    'orders.pendingConfirmation': 'Pending Confirmation',
    'orders.technicalLogs': 'Technical Logs',
    'orders.downloadFullLog': 'Download Full Log',

    // Withdraw
    'withdraw.title': 'Withdrawals',
    'withdraw.subtitle': 'Manage your payouts and fund withdrawals.',
    'withdraw.availableBalance': 'Available for Withdraw',
    'withdraw.pending': 'Pending Processing',
    'withdraw.processed24h': 'Processed (24h)',
    'withdraw.securityDelay': 'Security Delay',
    'withdraw.recent': 'Recent Withdrawals',
    'withdraw.request': 'Request Withdrawal',
    'withdraw.batch': 'Batch Withdraw',
    'withdraw.history': 'Withdrawal History',
    'withdraw.method': 'Method',
    'withdraw.destination': 'Destination',
    'withdraw.fee': 'Fee',
    'withdraw.sentTo': 'sent to',
    'withdraw.receipt': 'Receipt',
    'withdraw.onExplorer': 'on Explorer',
    'withdraw.transactionHash': 'Transaction Hash',
    'withdraw.networkFee': 'Network Fee',
    'withdraw.confirmations': 'Confirmations',
    'withdraw.newWithdrawal': 'New Withdrawal',
    'withdraw.createSubtitle': 'Request a new fund withdrawal',
    'withdraw.viewingDetails': 'Viewing details for',
    'withdraw.transactionDetails': 'Transaction Details',
    'withdraw.transferDetails': 'Transfer Details',
    'withdraw.enterDetails': 'Enter withdrawal details',
    'withdraw.selectAsset': 'Select Asset',
    'withdraw.available': 'Available',
    'withdraw.destinationAddress': 'Destination Address',
    'withdraw.totalDeduction': 'Total Deduction',
    'withdraw.confirmWithdrawal': 'Confirm Withdrawal',
    'withdraw.securityNotice': 'Security Notice',
    'withdraw.securityText': 'All withdrawals undergo a 24-hour security review before processing. High-value transactions may require additional verification.',
    'withdraw.availableForWithdrawal': 'Available for Withdrawal',
    'withdraw.totalWithdrawn': 'Total Withdrawn',
    'withdraw.withdrawalHistory': 'Withdrawal History',
    'withdraw.addressBook': 'Address Book',
    'withdraw.approvalProcess': 'Approval Process',
    'withdraw.withdrawalLimits': 'Withdrawal Limits',
    'withdraw.savedAddresses': 'Saved Withdrawal Addresses',
    'withdraw.manageAddresses': 'Manage your frequently used withdrawal addresses',
    'withdraw.addAddress': 'Add Address',
    'withdraw.label': 'Label',
    'withdraw.address': 'Address',
    'withdraw.network': 'Network',
    'withdraw.lastUsed': 'Last Used',
    'withdraw.actions': 'Actions',
    'withdraw.verified': 'Verified',
    'withdraw.unverified': 'Unverified',
    'withdraw.pendingApprovals': 'Pending Approvals',
    'withdraw.withdrawalsAwaitingApproval': 'Withdrawals awaiting approval',
    'withdraw.requestedBy': 'Requested by',
    'withdraw.on': 'on',
    'withdraw.reject': 'Reject',
    'withdraw.approve': 'Approve',
    'withdraw.approvalWorkflow': 'Approval Workflow',
    'withdraw.multiLevelApproval': 'Multi-level approval requirements',
    'withdraw.level': 'Level',
    'withdraw.level1Desc': 'Amounts under $10,000 require single approval from Finance Manager',
    'withdraw.level2Desc': 'Amounts $10,000-$50,000 require two approvals: Finance Manager + Director',
    'withdraw.level3Desc': 'Amounts over $50,000 require three approvals including CEO',
    'withdraw.withdrawalLimitsTitle': 'Withdrawal Limits',
    'withdraw.manageLimits': 'Monitor and manage your withdrawal limits',
    'withdraw.requestIncrease': 'Request Increase',
    'withdraw.dailyLimit': 'Daily Limit',
    'withdraw.weeklyLimit': 'Weekly Limit',
    'withdraw.monthlyLimit': 'Monthly Limit',
    'withdraw.remaining': 'remaining',
    'withdraw.resetsIn': 'Resets in',
    'withdraw.today': 'today',
    'withdraw.thisWeek': 'this week',
    'withdraw.thisMonth': 'this month',
    'withdraw.resetsOn': 'Resets on',
    'withdraw.needHigherLimits': 'Need higher limits?',
    'withdraw.contactManager': 'Contact your account manager or submit a limit increase request. Approval typically takes 24-48 hours.',
    'withdraw.requestLimitIncrease': 'Request Limit Increase',

    // Integration
    'integration.title': 'Integration Center',
    'integration.subtitle': 'Manage API keys, webhooks, and payment tools.',
    'integration.tabs.apiKeys': 'API Keys',
    'integration.tabs.webhooks': 'Webhooks',
    'integration.tabs.buttons': 'Payment Buttons',
    'integration.apiCredentials': 'API Credentials',
    'integration.apiDesc': 'Manage your API keys for backend integration.',
    'integration.clientId': 'Client ID',
    'integration.apiKey': 'API Key',
    'integration.apiKeyWarning': 'Keep this key secret! Do not share it.',
    'integration.resetApiKey': 'Reset API Key',
    'integration.webhookConfig': 'Webhook Configuration',
    'integration.webhookDesc': 'Configure webhook endpoints for real-time notifications.',
    'integration.endpointUrl': 'Endpoint URL',
    'integration.events': 'Events',
    'integration.addEndpoint': 'Add Endpoint',
    'integration.buttonConfig': 'Button Configuration',
    'integration.buttonDesc': 'Generate copy-paste payment buttons for your website.',
    'integration.itemName': 'Item Name',
    'integration.token': 'Token',
    'integration.network': 'Network',
    'integration.generatedCode': 'Generated Code',
    'integration.preview': 'Preview',
    'integration.copyCode': 'Copy Code',
    'integration.payWithCrypto': 'Pay with Crypto',
    'integration.apiDocs': 'API Documentation',
    'integration.apiKeys': 'API Keys',
    'integration.webhooks': 'Webhooks',
    'integration.paymentButtons': 'Payment Buttons',
    'action.remove': 'Remove',

    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account preferences and configurations.',
    'settings.general': 'General',
    'settings.verification': 'Verification',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.fees': 'Fees & Pricing',
    'settings.financial': 'Financial',
    'settings.branding': 'Branding',
    'settings.team': 'Team',
    'settings.invoice': 'Invoice',
    'settings.profileInfo': 'Profile Information',
    'settings.profileDesc': 'Update your personal details and timezone.',
    'settings.fullName': 'Full Name',
    'settings.email': 'Email Address',
    'settings.phone': 'Phone Number',
    'settings.phoneNumber': 'Phone Number',
    'settings.timezone': 'Timezone',
    'settings.businessVerification': 'Business Verification',
    'settings.verificationDesc': 'Verify your business to increase limits.',
    'settings.level1Verified': 'Level 1 Verified',
    'settings.dailyLimit': 'Daily Limit',
    'settings.monthlyLimit': 'Monthly Limit',
    'settings.withdrawals': 'Withdrawals',
    'settings.instant': 'Instant',
    'settings.requiresLevel2': 'Requires Level 2',
    'settings.upgradeLevel2': 'Upgrade to Level 2',
    'settings.upgradeDesc': 'Unlock higher limits and advanced features by verifying your business.',
    'settings.startVerification': 'Start Verification',
    'settings.autoSweepConfig': 'Auto-Sweep Configuration',
    'settings.autoSweepDesc': 'Configure automatic fund sweeping rules.',
    'settings.enableAutoSweep': 'Enable Auto-Sweep',
    'settings.enableAutoSweepDesc': 'Automatically sweep funds when threshold is met.',
    'settings.sweepMode': 'Sweep Mode',
    'settings.instantMode': 'Instant (High Gas)',
    'settings.hourlyMode': 'Hourly',
    'settings.nightlyMode': 'Nightly (Low Gas)',
    'settings.nightlyDesc': 'Nightly mode saves up to 90% on gas fees by batching transactions.',
    'settings.minThreshold': 'Minimum Threshold',
    'settings.targetCurrency': 'Target Currency',
    'settings.invoiceEntity': 'Invoice Entity',
    'settings.invoiceEntityDesc': 'Manage your business entity details for invoices.',
    'settings.legalName': 'Legal Business Name',
    'settings.taxId': 'Tax ID / VAT Number',
    'settings.businessAddress': 'Business Address',
    'settings.streetAddress': 'Street Address',
    'settings.city': 'City',
    'settings.postalCode': 'Postal Code',
    'settings.country': 'Country',
    'settings.autoGenInvoice': 'Auto-Generate Invoices',
    'settings.autoGenInvoiceDesc': 'Automatically generate invoices for all new orders.',

    // Email Notifications
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsDesc': 'Manage email notification preferences',
    'settings.paymentReceived': 'Payment Received',
    'settings.paymentReceivedDesc': 'Notify me when a payment is successfully received',
    'settings.paymentFailed': 'Payment Failed',
    'settings.paymentFailedDesc': 'Notify me when a payment fails or is rejected',
    'settings.withdrawalCompleted': 'Withdrawal Completed',
    'settings.withdrawalCompletedDesc': 'Notify me when withdrawals are processed',
    'settings.weeklySummary': 'Weekly Summary',
    'settings.weeklySummaryDesc': 'Send me a weekly summary of transactions',
    'settings.apiUsageAlerts': 'API Usage Alerts',
    'settings.apiUsageAlertsDesc': 'Alert me when API usage exceeds thresholds',

    // SMS Notifications
    'settings.smsNotifications': 'SMS Notifications',
    'settings.smsNotificationsDesc': 'Manage SMS notification preferences',
    'settings.largeTransactions': 'Large Transactions',
    'settings.largeTransactionsDesc': 'Alert me for transactions over $10,000',
    'settings.securityAlerts': 'Security Alerts',
    'settings.securityAlertsDesc': 'Notify me of suspicious account activity',
    'settings.systemMaintenance': 'System Maintenance',
    'settings.systemMaintenanceDesc': 'Notify me about scheduled maintenance',

    // Webhook Notifications
    'settings.webhookNotifications': 'Webhook Notifications',
    'settings.webhookNotificationsDesc': 'Configure webhook retry policies',
    'settings.webhookRetries': 'Automatic Retries',
    'settings.webhookRetriesDesc': 'Retry failed webhook deliveries automatically',
    'settings.maxRetryAttempts': 'Max Retry Attempts',
    'settings.attemptCount': '{count} attempts',

    // Security Settings
    'settings.twoFactorAuth': 'Two-Factor Authentication',
    'settings.twoFactorAuthDesc': 'Enhance your account security with 2FA',
    'settings.twoFactorEnabled': '2FA Enabled',
    'settings.lastVerified': 'Last verified',
    'settings.disable2FA': 'Disable 2FA',
    'settings.backupCodes': 'Backup Codes',
    'settings.backupCodesDesc': 'Save these codes in a secure location for account recovery',
    'settings.ipWhitelist': 'IP Whitelisting',
    'settings.ipWhitelistDesc': 'Restrict API access to specific IP addresses',
    'settings.enableIpWhitelisting': 'Enable IP Whitelisting',
    'settings.enableIpWhitelistingDesc': 'Only allow API requests from whitelisted IPs',
    'settings.whitelistedIPs': 'Whitelisted IP Addresses',
    'settings.addIP': 'Add IP',
    'settings.loginSessions': 'Active Login Sessions',
    'settings.loginSessionsDesc': 'Manage devices with active access to your account',
    'settings.current': 'Current',
    'settings.activeNow': 'Active now',
    'settings.hoursAgo': '{count}h ago',
    'settings.daysAgo': '{count}d ago',
    'settings.revoke': 'Revoke',
    'settings.revokeAllOtherSessions': 'Revoke All Other Sessions',

    // Fee Settings
    'settings.transactionFeeRates': 'Transaction Fee Rates',
    'settings.transactionFeeRatesDesc': 'Your current fee tier and rates',
    'settings.volumeBasedPricing': 'Volume-Based Pricing',
    'settings.volumeBasedPricingDesc': 'Your fee rate decreases as your monthly volume grows',
    'settings.standardTier': 'Standard Tier',
    'settings.growthTier': 'Growth Tier',
    'settings.enterpriseTier': 'Enterprise Tier',
    'settings.currentTier': 'Current',
    'settings.perMonth': 'month',
    'settings.percentageFee': 'Percentage Fee',
    'settings.perTransaction': 'Per Transaction',
    'settings.withdrawalFees': 'Withdrawal Fees',
    'settings.withdrawalFeesDesc': 'Network fees for different cryptocurrencies',

    // Branding Settings
    'settings.paymentPageCustomization': 'Payment Page Customization',
    'settings.paymentPageCustomizationDesc': 'Customize your payment page appearance',
    'settings.businessLogo': 'Business Logo',
    'settings.uploadLogo': 'Upload Logo',
    'settings.recommendedLogoSize': 'Recommended: 200x200px PNG or SVG',
    'settings.brandColor': 'Brand Color',
    'settings.supportLink': 'Support Link',
    'settings.saveBranding': 'Save Branding',

    // Team Settings
    'settings.teamMembers': 'Team Members',
    'settings.teamMembersDesc': 'Manage access for your team',
    'settings.inviteMember': 'Invite Member',
    'settings.invited': 'Invited',
    'settings.roleOwner': 'Owner',
    'settings.roleAdmin': 'Admin',
    'settings.roleDeveloper': 'Developer',
    'settings.roleFinance': 'Finance',
    'settings.roleReadOnly': 'Read Only',
    'settings.rolePermissions': 'Role Permissions',
    'settings.rolePermissionsDesc': 'Permissions for each role',
    'settings.roleOwnerPermissions': 'Full access to all features and settings',
    'settings.roleAdminPermissions': 'Manage team, settings, and API keys',
    'settings.roleDeveloperPermissions': 'Access to API keys and integrations only',
    'settings.roleFinancePermissions': 'View transactions and manage withdrawals',
    'settings.roleReadOnlyPermissions': 'View-only access to all data',

    // KYB
    'kyb.title': 'Verify your Business',
    'kyb.subtitle': 'Complete the KYB process to activate your crypto wallet and start accepting payments. Your progress is saved automatically.',
    'kyb.draftSaved': 'Draft saved',
    'kyb.step': 'Step',
    'kyb.of': 'of',
    'kyb.next': 'Next',
    'kyb.review': 'Review',
    'kyb.step1': 'Identity',
    'kyb.step2': 'Location',
    'kyb.step3': 'Documents',
    'kyb.dba': 'Doing Business As (DBA)',
    'kyb.optional': 'Optional',
    'kyb.regNumber': 'Registration Number',
    'kyb.website': 'Company Website',
    'kyb.countryInc': 'Country of Incorporation',
    'kyb.selectCountry': 'Select country...',
    'kyb.state': 'State / Province',
    'kyb.certInc': 'Certificate of Incorporation',
    'kyb.proofAddress': 'Proof of Address',
    'kyb.clickUpload': 'Click to upload',
    'kyb.dragDrop': 'or drag and drop',
    'kyb.saveDraft': 'Save as Draft',
    'kyb.whyNeed': 'Why do we need this?',
    'kyb.whyNeedDesc': 'As a regulated financial institution, we are required to collect and verify information about your business to comply with',
    'kyb.aml': 'Anti-Money Laundering (AML)',
    'kyb.regulations': 'regulations',
    'kyb.docGuidelines': 'Document Guidelines',
    'kyb.guide1': 'Must be issued within last 3 months',
    'kyb.guide2': 'All 4 corners must be visible',
    'kyb.guide3': 'Text must be clearly legible',
    'kyb.guide4': 'No screenshots allowed',
    'kyb.needHelp': 'Need Help?',
    'kyb.contactSupportDesc': 'Our compliance team is available to assist you.',
    'kyb.contactSupport': 'Contact Support',

    // Create Order
    'createOrder.title': 'Create Order',
    'createOrder.subtitle': 'Generate a payment link manually',
    'createOrder.orderDetails': 'Order Details',
    'createOrder.amount': 'Amount',
    'createOrder.currency': 'Currency',
    'createOrder.network': 'Network',
    'createOrder.customerEmail': 'Customer Email',
    'createOrder.customerEmailOptional': 'Customer Email (Optional)',
    'createOrder.generateLink': 'Generate Payment Link',
    'createOrder.awaitingPayment': 'Awaiting Payment',
    'createOrder.paymentSuccessful': 'Payment Successful',
    'createOrder.scanToPay': 'Scan to pay',
    'createOrder.paymentAddress': 'Payment Address',
    'createOrder.timeRemaining': 'Time Remaining',
    'createOrder.detectingPayment': 'Detecting payment on-chain...',
    'createOrder.simulatePayment': '[Simulate Payment Received]',
    'createOrder.createAnother': 'Create Another Order',
    'createOrder.paid': 'Paid',
    'createOrder.transactionConfirmed': 'Transaction confirmed on blockchain',

    // Invoice
    'invoice.title': 'Create Invoice',
    'invoice.subtitle': 'Generate professional crypto invoices for your clients.',
    'invoice.saveDraft': 'Save Draft',
    'invoice.invoiceDetails': 'Invoice Details',
    'invoice.invoiceNumber': 'Invoice Number',
    'invoice.dueDate': 'Due Date',
    'invoice.clientEmail': 'Client Email',
    'invoice.lineItems': 'Line Items',
    'invoice.description': 'Description',
    'invoice.serviceOrProduct': 'Service or Product',
    'invoice.amount': 'Amount',
    'invoice.currency': 'Currency',
    'invoice.addItem': '+ Add Item',
    'invoice.notes': 'Notes',
    'invoice.notesPlaceholder': 'Thank you for your business...',
    'invoice.summary': 'Summary',
    'invoice.subtotal': 'Subtotal',
    'invoice.tax': 'Tax',
    'invoice.total': 'Total',
    'invoice.sendInvoice': 'Send Invoice',
    'invoice.shareLink': 'Share Link',
    'invoice.paymentLink': 'Payment Link',
    'invoice.overview': 'Invoice Overview',
    'invoice.viewInvoice': 'View Invoice',
    'invoice.downloadInvoice': 'Download Invoice',
    'invoice.invoiceStatus': 'Invoice Status',
    'invoice.paid': 'Paid',
    'invoice.unpaid': 'Unpaid',
    'invoice.issueDate': 'Issue Date',
    'invoice.generatedFor': 'Generated for',

    // Common
    'common.loading': 'Loading',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.selected': 'selected',
    'common.clear': 'Clear',
    'common.apply': 'Apply',
    'common.advancedFilters': 'Advanced',
    'common.dateRange': 'Date Range',
    'common.from': 'From',
    'common.to': 'To',
    'common.amountRange': 'Amount Range',
    'common.min': 'Min',
    'common.max': 'Max',
    'common.allNetworks': 'All Networks',
    'common.searchBy': 'Search by',
    'common.cryptocurrency': 'Cryptocurrency',
    'common.allCurrencies': 'All Currencies',
    'common.clearFilters': 'Clear Filters',
    'common.applyFilters': 'Apply Filters',
    'common.noResultsFound': 'No orders found',
    'common.tryAdjusting': 'Try adjusting your filters',
    'common.exportSelected': 'Export Selected',
    'common.markComplete': 'Mark Complete',
    'common.rate': 'Rate',
    'common.explorer': 'Explorer',
    'common.invoiceId': 'Invoice ID',
    'common.coin': 'Coin',
    'common.created': 'Created',
    'common.fromTo': 'From → To',
    'common.time': 'Time',
    'common.dueDate': 'Due Date',

    // Order Status Flow
    'orderFlow.title': 'Order Status Flow',
    'orderFlow.statusFlow': 'Status Flow',
    'orderFlow.created': 'Created',
    'orderFlow.paymentDetected': 'Payment Detected',
    'orderFlow.confirming': 'Confirming',
    'orderFlow.completed': 'Completed',
    'orderFlow.orderInitialized': 'Order initialized',
    'orderFlow.transactionFound': 'Transaction found',
    'orderFlow.awaitingConfirmations': 'Awaiting confirmations',
    'orderFlow.orderFinalized': 'Order finalized',
    'orderFlow.failedState': 'Failed State',
    'orderFlow.failedDescription': 'If payment fails or expires, the order moves to Failed state. Failed orders can be retried or cancelled.',

    // Networks
    'network.ethereum': 'Ethereum',
    'network.ethereumMainnet': 'Ethereum Mainnet',
    'network.erc20Token': 'ERC-20 Token',
    'network.polygon': 'Polygon',
    'network.bsc': 'BSC',
    'network.arbitrum': 'Arbitrum',
    'network.tronTrc20': 'TRON (TRC20)',
    'network.ethereumErc20': 'Ethereum (ERC20)',
    'network.bscBep20': 'BSC (BEP20)',

    // 404 Page
    'notFound.title': '404',
    'notFound.pageNotFound': 'Page Not Found',
    'notFound.description': 'Sorry, the page you are looking for doesn\'t exist.',
    'notFound.subDescription': 'It may have been moved or deleted.',
    'notFound.goHome': 'Go Home',
  },
  zh: {
    // Navigation
    'nav.dashboard': '仪表盘',
    'nav.assets': '资产管理',
    'nav.orders': '订单记录',
    'nav.integration': '集成中心',
    'nav.withdraw': '提现管理',
    'nav.settings': '系统设置',
    'nav.signout': '退出登录',
    'nav.merchantPortal': '商户门户 v2.1',

    // Dashboard
    'dashboard.welcome': '欢迎回来，商户。这是您的财务概览。',
    'dashboard.revenue': '总收入',
    'dashboard.activeOrders': '活跃订单',
    'dashboard.pendingPayouts': '待处理提现',
    'dashboard.accountStatus': '账户状态',
    'dashboard.quickActions': '快捷操作',
    'dashboard.revenueOverview': '收入概览',
    'dashboard.completeProfile': '完善您的资料',
    'dashboard.completeProfileDesc': '添加您的企业实体信息以启用自动发票功能。',
    'dashboard.goToSettings': '前往设置',
    'dashboard.fromLastMonth': '与上月相比',
    'dashboard.sinceLastHour': '过去一小时',
    'dashboard.scheduledTonight': '计划今晚处理',
    'dashboard.transactions': '交易',
    'dashboard.transactionHistory': '交易历史',

    // Actions
    'action.createInvoice': '创建发票',
    'action.withdraw': '提现',
    'action.apiKeys': 'API 密钥',
    'action.settings': '设置',
    'action.copy': '复制',
    'action.copied': '已复制',
    'action.view': '查看',
    'action.download': '下载',
    'action.filter': '筛选',
    'action.export': '导出',
    'action.search': '搜索',
    'action.save': '保存更改',
    'action.cancel': '取消',
    'action.generate': '生成',
    'action.regenerate': '重新生成',
    'action.delete': '删除',
    'action.edit': '编辑',
    'action.verify': '立即认证',
    'action.continue': '继续',
    'action.remove': '移除',

    // Status
    'status.active': '活跃',
    'status.verified': '二级认证通过',
    'status.kybVerified': 'KYB 已认证',
    'status.systemActive': '系统运行中',
    'status.completed': '已完成',
    'status.pending': '待处理',
    'status.processing': '处理中',
    'status.failed': '失败',
    'status.cancelled': '已取消',
    'status.refunded': '已退款',

    // Assets
    'assets.title': '资产管理',
    'assets.subtitle': '监控您的多链余额和归集状态。',
    'assets.totalBalance': '总余额',
    'assets.swept': '已归集 (冷钱包)',
    'assets.unswept': '未归集 (热钱包)',
    'assets.autoSweep': '自动归集',
    'assets.on': '开启',
    'assets.off': '关闭',
    'assets.asset': '资产',
    'assets.chain': '链',
    'assets.balance': '余额',
    'assets.value': '价值 (USD)',
    'assets.status': '状态',
    'assets.action': '操作',
    'assets.sweepNow': '立即归集',
    'assets.overview': '概览',
    'assets.sweepStrategy': '归集策略',
    'assets.addressManagement': '地址管理',
    'assets.nextBatch': '下一批',
    'assets.lastSweep': '上次归集',
    'assets.hoursAgo': '小时前',
    'assets.addressesProcessed': '个地址已处理',
    'assets.autoSweepConfig': '自动归集配置',
    'assets.autoSweepConfigDesc': '配置资金自动归集到冷钱包',
    'assets.sweepThreshold': '归集阈值',
    'assets.sweepThresholdDesc': '触发归集的最低余额',
    'assets.schedule': '计划',
    'assets.everyHour': '每小时',
    'assets.every4Hours': '每 4 小时',
    'assets.dailyAt2AM': '每日凌晨 2 点 UTC',
    'assets.manualOnly': '仅手动',
    'assets.scheduleDesc': '何时自动归集资金',
    'assets.targetSweepAddress': '目标归集地址',
    'assets.targetSweepAddressDesc': '资金将发送到的冷钱包地址',
    'assets.gasPriceStrategy': 'Gas 价格策略',
    'assets.slow': '慢速 (低成本)',
    'assets.standard': '标准',
    'assets.fast': '快速 (高成本)',
    'assets.testSweep': '测试归集',
    'assets.recentSweepHistory': '最近归集历史',
    'assets.time': '时间',
    'assets.addresses': '地址',
    'assets.manualSweep': '手动归集',
    'assets.manualSweepDesc': '立即触发所有符合条件地址的归集',
    'assets.startSweepNow': '立即开始归集',
    'assets.sweepStatistics': '归集统计',
    'assets.totalSwept30d': '30天总归集量',
    'assets.gasFeesSpent': 'Gas 费用支出',
    'assets.depositAddresses': '充值地址',
    'assets.depositAddressesDesc': '管理和监控您的充值地址',
    'assets.allAssets': '所有资产',
    'assets.generateAddress': '生成地址',
    'assets.label': '标签',
    'assets.address': '地址',
    'assets.transactions': '交易',
    'assets.lastActivity': '最后活动',
    'status.idle': '空闲',

    // Orders
    'orders.title': '订单历史',
    'orders.subtitle': '查看和管理您的交易记录。',
    'orders.orderId': '订单号',
    'orders.customer': '客户',
    'orders.amount': '金额',
    'orders.date': '日期',
    'orders.paymentMethod': '支付方式',
    'orders.invoice': '发票',
    'orders.allStatus': '全部状态',
    'orders.allTypes': '全部类型',
    'orders.type': '类型',
    'orders.payment': '支付',
    'orders.payout': '提现',
    'orders.onExplorer': '在区块浏览器查看',
    'orders.csv': 'CSV',
    'orders.createdOn': '创建于',
    'orders.totalAmount': '总金额',
    'orders.fiatEquivalent': '法币等值',
    'orders.timeRemaining': '剩余时间',
    'orders.paymentDetails': '支付详情',
    'orders.network': '网络',
    'orders.destination': '目标地址',
    'orders.txHash': '交易哈希',
    'orders.blockHeight': '区块高度',
    'orders.confirmations': '确认数',
    'orders.timeline': '支付时间线',
    'orders.orderCreated': '订单创建',
    'orders.paymentDetected': '检测到支付',
    'orders.confirming': '确认中',
    'orders.inProgress': '进行中',
    'orders.pendingConfirmation': '等待确认',
    'orders.technicalLogs': '技术日志',
    'orders.downloadFullLog': '下载完整日志',

    // Withdraw
    'withdraw.title': '提现管理',
    'withdraw.subtitle': '管理您的资金提现和转账。',
    'withdraw.availableBalance': '可提现余额',
    'withdraw.pending': '待处理',
    'withdraw.processed24h': '24小时内已处理',
    'withdraw.securityDelay': '安全延迟',
    'withdraw.recent': '最近提现',
    'withdraw.request': '申请提现',
    'withdraw.batch': '批量提现',
    'withdraw.history': '提现历史',
    'withdraw.method': '方式',
    'withdraw.destination': '目标地址',
    'withdraw.fee': '手续费',
    'withdraw.sentTo': '发送至',
    'withdraw.receipt': '收据',
    'withdraw.onExplorer': '在区块浏览器查看',
    'withdraw.transactionHash': '交易哈希',
    'withdraw.networkFee': '网络费用',
    'withdraw.confirmations': '确认数',
    'withdraw.newWithdrawal': '新建提现',
    'withdraw.createSubtitle': '申请新的资金提现',
    'withdraw.viewingDetails': '查看详情',
    'withdraw.transactionDetails': '交易详情',
    'withdraw.transferDetails': '转账详情',
    'withdraw.enterDetails': '输入提现详情',
    'withdraw.selectAsset': '选择资产',
    'withdraw.available': '可用',
    'withdraw.destinationAddress': '目标地址',
    'withdraw.totalDeduction': '总扣除',
    'withdraw.confirmWithdrawal': '确认提现',
    'withdraw.securityNotice': '安全提示',
    'withdraw.securityText': '所有提现申请将经过24小时安全审查后处理。大额交易可能需要额外验证。',
    'withdraw.availableForWithdrawal': '可提现',
    'withdraw.totalWithdrawn': '已提现总额',
    'withdraw.withdrawalHistory': '提现历史',
    'withdraw.addressBook': '地址簿',
    'withdraw.approvalProcess': '审批流程',
    'withdraw.withdrawalLimits': '提现限额',
    'withdraw.savedAddresses': '已保存的提现地址',
    'withdraw.manageAddresses': '管理您常用的提现地址',
    'withdraw.addAddress': '添加地址',
    'withdraw.label': '标签',
    'withdraw.address': '地址',
    'withdraw.network': '网络',
    'withdraw.lastUsed': '最后使用',
    'withdraw.actions': '操作',
    'withdraw.verified': '已验证',
    'withdraw.unverified': '未验证',
    'withdraw.pendingApprovals': '待审批',
    'withdraw.withdrawalsAwaitingApproval': '等待审批的提现',
    'withdraw.requestedBy': '申请人',
    'withdraw.on': '于',
    'withdraw.reject': '拒绝',
    'withdraw.approve': '批准',
    'withdraw.approvalWorkflow': '审批工作流',
    'withdraw.multiLevelApproval': '多级审批要求',
    'withdraw.level': '级别',
    'withdraw.level1Desc': '金额低于 $10,000 需要财务经理单人审批',
    'withdraw.level2Desc': '金额 $10,000-$50,000 需要两级审批：财务经理 + 总监',
    'withdraw.level3Desc': '金额超过 $50,000 需要三级审批，包括 CEO',
    'withdraw.withdrawalLimitsTitle': '提现限额',
    'withdraw.manageLimits': '监控和管理您的提现限额',
    'withdraw.requestIncrease': '申请提高额度',
    'withdraw.dailyLimit': '每日限额',
    'withdraw.weeklyLimit': '每周限额',
    'withdraw.monthlyLimit': '每月限额',
    'withdraw.remaining': '剩余',
    'withdraw.resetsIn': '重置时间',
    'withdraw.today': '今天',
    'withdraw.thisWeek': '本周',
    'withdraw.thisMonth': '本月',
    'withdraw.resetsOn': '重置于',
    'withdraw.needHigherLimits': '需要更高额度？',
    'withdraw.contactManager': '联系您的客户经理或提交额度提高申请。审批通常需要24-48小时。',
    'withdraw.requestLimitIncrease': '申请提高额度',

    // Integration
    'integration.title': '集成中心',
    'integration.subtitle': '管理 API 密钥、Webhook 和支付工具。',
    'integration.tabs.apiKeys': 'API 密钥',
    'integration.tabs.webhooks': 'Webhooks',
    'integration.tabs.buttons': '支付按钮',
    'integration.apiCredentials': 'API 凭证',
    'integration.apiDesc': '管理用于后端集成的 API 密钥。',
    'integration.clientId': '客户端 ID',
    'integration.apiKey': 'API 密钥',
    'integration.apiKeyWarning': '请妥善保管此密钥！切勿泄露。',
    'integration.resetApiKey': '重置 API 密钥',
    'integration.webhookConfig': 'Webhook 配置',
    'integration.webhookDesc': '配置用于实时通知的 Webhook 端点。',
    'integration.endpointUrl': '端点 URL',
    'integration.events': '事件',
    'integration.addEndpoint': '添加端点',
    'integration.buttonConfig': '按钮配置',
    'integration.buttonDesc': '生成可直接复制粘贴到您网站的支付按钮代码。',
    'integration.itemName': '商品名称',
    'integration.token': '代币',
    'integration.network': '网络',
    'integration.generatedCode': '生成代码',
    'integration.preview': '预览',
    'integration.copyCode': '复制代码',
    'integration.payWithCrypto': '使用加密货币支付',
    'integration.apiDocs': 'API 文档',
    'integration.apiKeys': 'API 密钥',
    'integration.webhooks': 'Webhooks',
    'integration.paymentButtons': '支付按钮',

    // Settings
    'settings.title': '系统设置',
    'settings.subtitle': '管理您的账户偏好和配置。',
    'settings.general': '常规',
    'settings.verification': '认证',
    'settings.notifications': '通知设置',
    'settings.security': '安全',
    'settings.fees': '费用与定价',
    'settings.financial': '财务',
    'settings.branding': '品牌定制',
    'settings.team': '团队',
    'settings.invoice': '发票',
    'settings.profileInfo': '个人信息',
    'settings.profileDesc': '更新您的个人详细信息和时区。',
    'settings.fullName': '全名',
    'settings.email': '电子邮件',
    'settings.phone': '电话号码',
    'settings.phoneNumber': '电话号码',
    'settings.timezone': '时区',
    'settings.businessVerification': '企业认证',
    'settings.verificationDesc': '验证您的企业以提高限额。',
    'settings.level1Verified': '一级认证通过',
    'settings.dailyLimit': '每日限额',
    'settings.monthlyLimit': '每月限额',
    'settings.withdrawals': '提现',
    'settings.instant': '即时',
    'settings.requiresLevel2': '需要二级认证',
    'settings.upgradeLevel2': '升级到二级认证',
    'settings.upgradeDesc': '通过验证您的企业来解锁更高限额和高级功能。',
    'settings.startVerification': '开始认证',
    'settings.autoSweepConfig': '自动归集配置',
    'settings.autoSweepDesc': '配置自动资金归集规则。',
    'settings.enableAutoSweep': '启用自动归集',
    'settings.enableAutoSweepDesc': '当达到阈值时自动归集资金。',
    'settings.sweepMode': '归集模式',
    'settings.instantMode': '即时 (高 Gas)',
    'settings.hourlyMode': '每小时',
    'settings.nightlyMode': '夜间 (低 Gas)',
    'settings.nightlyDesc': '夜间模式通过批量处理交易可节省高达 90% 的 Gas 费。',
    'settings.minThreshold': '最低阈值',
    'settings.targetCurrency': '目标货币',
    'settings.invoiceEntity': '发票实体',
    'settings.invoiceEntityDesc': '管理发票上的企业实体详细信息。',
    'settings.legalName': '法定企业名称',
    'settings.taxId': '税号 / VAT',
    'settings.businessAddress': '企业地址',
    'settings.streetAddress': '街道地址',
    'settings.city': '城市',
    'settings.postalCode': '邮政编码',
    'settings.country': '国家',
    'settings.autoGenInvoice': '自动生成发票',
    'settings.autoGenInvoiceDesc': '为所有新订单自动生成发票。',

    // Email Notifications
    'settings.emailNotifications': '邮件通知',
    'settings.emailNotificationsDesc': '管理邮件通知偏好',
    'settings.paymentReceived': '收到支付',
    'settings.paymentReceivedDesc': '成功收到支付时通知我',
    'settings.paymentFailed': '支付失败',
    'settings.paymentFailedDesc': '支付失败或被拒绝时通知我',
    'settings.withdrawalCompleted': '提现完成',
    'settings.withdrawalCompletedDesc': '提现处理完成时通知我',
    'settings.weeklySummary': '每周摘要',
    'settings.weeklySummaryDesc': '发送每周交易摘要',
    'settings.apiUsageAlerts': 'API 使用警报',
    'settings.apiUsageAlertsDesc': 'API 使用超过阈值时提醒我',

    // SMS Notifications
    'settings.smsNotifications': '短信通知',
    'settings.smsNotificationsDesc': '管理短信通知偏好',
    'settings.largeTransactions': '大额交易',
    'settings.largeTransactionsDesc': '超过 $10,000 的交易提醒我',
    'settings.securityAlerts': '安全警报',
    'settings.securityAlertsDesc': '可疑账户活动时通知我',
    'settings.systemMaintenance': '系统维护',
    'settings.systemMaintenanceDesc': '计划维护时通知我',

    // Webhook Notifications
    'settings.webhookNotifications': 'Webhook 通知',
    'settings.webhookNotificationsDesc': '配置 webhook 重试策略',
    'settings.webhookRetries': '自动重试',
    'settings.webhookRetriesDesc': '自动重试失败的 webhook 传递',
    'settings.maxRetryAttempts': '最大重试次数',
    'settings.attemptCount': '{count} 次尝试',

    // Security Settings
    'settings.twoFactorAuth': '双因素认证',
    'settings.twoFactorAuthDesc': '使用 2FA 增强账户安全性',
    'settings.twoFactorEnabled': '2FA 已启用',
    'settings.lastVerified': '上次验证',
    'settings.disable2FA': '禁用 2FA',
    'settings.backupCodes': '备份代码',
    'settings.backupCodesDesc': '将这些代码保存在安全位置以便账户恢复',
    'settings.ipWhitelist': 'IP 白名单',
    'settings.ipWhitelistDesc': '限制 API 访问特定 IP 地址',
    'settings.enableIpWhitelisting': '启用 IP 白名单',
    'settings.enableIpWhitelistingDesc': '仅允许来自白名单 IP 的 API 请求',
    'settings.whitelistedIPs': '白名单 IP 地址',
    'settings.addIP': '添加 IP',
    'settings.loginSessions': '活动登录会话',
    'settings.loginSessionsDesc': '管理可访问您账户的设备',
    'settings.current': '当前',
    'settings.activeNow': '活跃中',
    'settings.hoursAgo': '{count} 小时前',
    'settings.daysAgo': '{count} 天前',
    'settings.revoke': '撤销',
    'settings.revokeAllOtherSessions': '撤销所有其他会话',

    // Fee Settings
    'settings.transactionFeeRates': '交易费率',
    'settings.transactionFeeRatesDesc': '您当前的费率等级',
    'settings.volumeBasedPricing': '基于交易量的定价',
    'settings.volumeBasedPricingDesc': '随着月交易量增长，费率会降低',
    'settings.standardTier': '标准等级',
    'settings.growthTier': '成长等级',
    'settings.enterpriseTier': '企业等级',
    'settings.currentTier': '当前',
    'settings.perMonth': '月',
    'settings.percentageFee': '百分比费用',
    'settings.perTransaction': '每笔交易',
    'settings.withdrawalFees': '提现费用',
    'settings.withdrawalFeesDesc': '不同加密货币的网络费用',

    // Branding Settings
    'settings.paymentPageCustomization': '支付页面定制',
    'settings.paymentPageCustomizationDesc': '自定义您的支付页面外观',
    'settings.businessLogo': '企业 Logo',
    'settings.uploadLogo': '上传 Logo',
    'settings.recommendedLogoSize': '推荐尺寸：200x200px PNG 或 SVG',
    'settings.brandColor': '品牌颜色',
    'settings.supportLink': '支持链接',
    'settings.saveBranding': '保存品牌设置',

    // Team Settings
    'settings.teamMembers': '团队成员',
    'settings.teamMembersDesc': '管理团队访问权限',
    'settings.inviteMember': '邀请成员',
    'settings.invited': '已邀请',
    'settings.roleOwner': '所有者',
    'settings.roleAdmin': '管理员',
    'settings.roleDeveloper': '开发者',
    'settings.roleFinance': '财务',
    'settings.roleReadOnly': '只读',
    'settings.rolePermissions': '角色权限',
    'settings.rolePermissionsDesc': '每个角色的权限',
    'settings.roleOwnerPermissions': '完全访问所有功能和设置',
    'settings.roleAdminPermissions': '管理团队、设置和 API 密钥',
    'settings.roleDeveloperPermissions': '仅访问 API 密钥和集成',
    'settings.roleFinancePermissions': '查看交易并管理提现',
    'settings.roleReadOnlyPermissions': '所有数据的只读访问',

    // KYB
    'kyb.title': '验证您的企业',
    'kyb.subtitle': '完成 KYB 流程以激活您的加密钱包并开始接受付款。您的进度会自动保存。',
    'kyb.draftSaved': '草稿已保存',
    'kyb.step': '步骤',
    'kyb.of': '/',
    'kyb.next': '下一步',
    'kyb.review': '审核',
    'kyb.step1': '身份',
    'kyb.step2': '位置',
    'kyb.step3': '文件',
    'kyb.dba': '经营名称 (DBA)',
    'kyb.optional': '可选',
    'kyb.regNumber': '注册号',
    'kyb.website': '公司网站',
    'kyb.countryInc': '注册国家',
    'kyb.selectCountry': '选择国家...',
    'kyb.state': '州 / 省',
    'kyb.certInc': '注册证书',
    'kyb.proofAddress': '地址证明',
    'kyb.clickUpload': '点击上传',
    'kyb.dragDrop': '或拖放文件',
    'kyb.saveDraft': '保存草稿',
    'kyb.whyNeed': '为什么需要这个？',
    'kyb.whyNeedDesc': '作为受监管的金融机构，我们需要收集和验证您的企业信息以遵守',
    'kyb.aml': '反洗钱 (AML)',
    'kyb.regulations': '法规',
    'kyb.docGuidelines': '文件指南',
    'kyb.guide1': '必须在过去 3 个月内签发',
    'kyb.guide2': '所有 4 个角必须可见',
    'kyb.guide3': '文字必须清晰可辨',
    'kyb.guide4': '不允许截图',
    'kyb.needHelp': '需要帮助？',
    'kyb.contactSupportDesc': '我们的合规团队随时为您提供帮助。',
    'kyb.contactSupport': '联系支持',

    // Create Order
    'createOrder.title': '创建订单',
    'createOrder.subtitle': '手动生成支付链接',
    'createOrder.orderDetails': '订单详情',
    'createOrder.amount': '金额',
    'createOrder.currency': '货币',
    'createOrder.network': '网络',
    'createOrder.customerEmail': '客户邮箱',
    'createOrder.customerEmailOptional': '客户邮箱（可选）',
    'createOrder.generateLink': '生成支付链接',
    'createOrder.awaitingPayment': '等待支付',
    'createOrder.paymentSuccessful': '支付成功',
    'createOrder.scanToPay': '扫码支付',
    'createOrder.paymentAddress': '支付地址',
    'createOrder.timeRemaining': '剩余时间',
    'createOrder.detectingPayment': '正在检测链上支付...',
    'createOrder.simulatePayment': '[模拟收到支付]',
    'createOrder.createAnother': '创建另一个订单',
    'createOrder.paid': '已支付',
    'createOrder.transactionConfirmed': '交易已在区块链上确认',

    // Invoice
    'invoice.title': '创建发票',
    'invoice.subtitle': '为您的客户生成专业的加密货币发票。',
    'invoice.saveDraft': '保存草稿',
    'invoice.invoiceDetails': '发票详情',
    'invoice.invoiceNumber': '发票编号',
    'invoice.dueDate': '到期日期',
    'invoice.clientEmail': '客户邮箱',
    'invoice.lineItems': '行项目',
    'invoice.description': '描述',
    'invoice.serviceOrProduct': '服务或产品',
    'invoice.amount': '金额',
    'invoice.currency': '货币',
    'invoice.addItem': '+ 添加项目',
    'invoice.notes': '备注',
    'invoice.notesPlaceholder': '感谢您的惠顾...',
    'invoice.summary': '摘要',
    'invoice.subtotal': '小计',
    'invoice.tax': '税费',
    'invoice.total': '总计',
    'invoice.sendInvoice': '发送发票',
    'invoice.shareLink': '分享链接',
    'invoice.paymentLink': '支付链接',
    'invoice.overview': '发票概览',
    'invoice.viewInvoice': '查看发票',
    'invoice.downloadInvoice': '下载发票',
    'invoice.invoiceStatus': '发票状态',
    'invoice.paid': '已支付',
    'invoice.unpaid': '未支付',
    'invoice.issueDate': '开票日期',
    'invoice.generatedFor': '开票对象',

    // Common
    'common.loading': '加载中',
    'common.error': '错误',
    'common.success': '成功',
    'common.selected': '已选中',
    'common.clear': '清除',
    'common.apply': '应用',
    'common.advancedFilters': '高级筛选',
    'common.dateRange': '日期范围',
    'common.from': '从',
    'common.to': '到',
    'common.amountRange': '金额范围',
    'common.min': '最小',
    'common.max': '最大',
    'common.allNetworks': '所有网络',
    'common.searchBy': '搜索',
    'common.cryptocurrency': '加密货币',
    'common.allCurrencies': '所有货币',
    'common.clearFilters': '清除筛选',
    'common.applyFilters': '应用筛选',
    'common.noResultsFound': '未找到订单',
    'common.tryAdjusting': '尝试调整您的筛选条件',
    'common.exportSelected': '导出选中',
    'common.markComplete': '标记完成',
    'common.rate': '汇率',
    'common.explorer': '区块浏览器',
    'common.invoiceId': '发票编号',
    'common.coin': '币种',
    'common.created': '创建时间',
    'common.fromTo': '从 → 到',
    'common.time': '时间',
    'common.dueDate': '到期日期',

    // Order Status Flow
    'orderFlow.title': '订单状态流程',
    'orderFlow.statusFlow': '状态流程',
    'orderFlow.created': '已创建',
    'orderFlow.paymentDetected': '检测到支付',
    'orderFlow.confirming': '确认中',
    'orderFlow.completed': '已完成',
    'orderFlow.orderInitialized': '订单已初始化',
    'orderFlow.transactionFound': '发现交易',
    'orderFlow.awaitingConfirmations': '等待确认',
    'orderFlow.orderFinalized': '订单已完成',
    'orderFlow.failedState': '失败状态',
    'orderFlow.failedDescription': '如果支付失败或过期，订单将转为失败状态。失败的订单可以重试或取消。',

    // Networks
    'network.ethereum': '以太坊',
    'network.ethereumMainnet': '以太坊主网',
    'network.erc20Token': 'ERC-20 代币',
    'network.polygon': 'Polygon',
    'network.bsc': 'BSC',
    'network.arbitrum': 'Arbitrum',
    'network.tronTrc20': 'TRON (TRC20)',
    'network.ethereumErc20': '以太坊 (ERC20)',
    'network.bscBep20': 'BSC (BEP20)',

    // 404 Page
    'notFound.title': '404',
    'notFound.pageNotFound': '页面未找到',
    'notFound.description': '抱歉，您访问的页面不存在。',
    'notFound.subDescription': '它可能已被移动或删除。',
    'notFound.goHome': '返回首页',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
