import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.assets': 'Assets',
    'nav.orders': 'Orders',
    'nav.integration': 'Integration',
    'nav.withdraw': 'Withdraw',
    'nav.settings': 'Settings',
    'nav.signout': 'Sign Out',
    'nav.merchantPortal': 'Merchant Portal v2.1',

    // Dashboard
    'dashboard.welcome': 'Welcome back, Merchant. Here\'s your financial overview.',
    'dashboard.revenue': 'Total Revenue',
    'dashboard.activeOrders': 'Active Orders',
    'dashboard.pendingPayouts': 'Pending Payouts',
    'dashboard.accountStatus': 'Account Status',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.revenueOverview': 'Revenue Overview',
    'dashboard.completeProfile': 'Complete your profile',
    'dashboard.completeProfileDesc': 'Add your business entity details to enable automatic invoicing features.',
    'dashboard.goToSettings': 'Go to Settings',
    'dashboard.fromLastMonth': 'from last month',
    'dashboard.sinceLastHour': 'since last hour',
    'dashboard.scheduledTonight': 'Scheduled for tonight',
    'dashboard.transactions': 'transactions',
    'dashboard.transactionHistory': 'Transaction History',

    // Actions
    'action.createInvoice': 'Create Invoice',
    'action.withdraw': 'Withdraw',
    'action.apiKeys': 'API Keys',
    'action.settings': 'Settings',
    'action.copy': 'Copy',
    'action.copied': 'Copied',
    'action.view': 'View',
    'action.download': 'Download',
    'action.filter': 'Filter',
    'action.export': 'Export',
    'action.search': 'Search',
    'action.save': 'Save Changes',
    'action.cancel': 'Cancel',
    'action.generate': 'Generate',
    'action.regenerate': 'Regenerate',
    'action.delete': 'Delete',
    'action.edit': 'Edit',
    'action.verify': 'Verify Now',
    'action.continue': 'Continue',

    // Status
    'status.active': 'Active',
    'status.verified': 'Level 2 Verified',
    'status.kybVerified': 'KYB Verified',
    'status.systemActive': 'System Active',
    'status.completed': 'Completed',
    'status.pending': 'Pending',
    'status.processing': 'Processing',
    'status.failed': 'Failed',
    'status.cancelled': 'Cancelled',
    'status.refunded': 'Refunded',

    // Assets
    'assets.title': 'Assets Management',
    'assets.subtitle': 'Monitor your multi-chain balances and sweeping status.',
    'assets.totalBalance': 'Total Balance',
    'assets.swept': 'Swept to Cold Wallet',
    'assets.unswept': 'Unswept (Hot Wallet)',
    'assets.autoSweep': 'Auto-Sweep',
    'assets.on': 'ON',
    'assets.off': 'OFF',
    'assets.asset': 'Asset',
    'assets.chain': 'Chain',
    'assets.balance': 'Balance',
    'assets.value': 'Value (USD)',
    'assets.status': 'Status',
    'assets.action': 'Action',
    'assets.sweepNow': 'Sweep Now',

    // Orders
    'orders.title': 'Order History',
    'orders.subtitle': 'View and manage your transaction records.',
    'orders.orderId': 'Order ID',
    'orders.customer': 'Customer',
    'orders.amount': 'Amount',
    'orders.date': 'Date',
    'orders.paymentMethod': 'Payment Method',
    'orders.invoice': 'Invoice',
    'orders.allStatus': 'All Status',
    'orders.allTypes': 'All Types',
    'orders.type': 'Type',
    'orders.payment': 'Payment',
    'orders.payout': 'Payout',
    'orders.onExplorer': 'on Explorer',
    'orders.csv': 'CSV',
    'orders.createdOn': 'Created on',
    'orders.totalAmount': 'Total Amount',
    'orders.fiatEquivalent': 'Fiat Equivalent',
    'orders.timeRemaining': 'Time Remaining',
    'orders.paymentDetails': 'Payment Details',
    'orders.network': 'Network',
    'orders.destination': 'Destination Address',
    'orders.txHash': 'Transaction Hash',
    'orders.blockHeight': 'Block Height',
    'orders.confirmations': 'Confirmations',
    'orders.timeline': 'Payment Timeline',
    'orders.orderCreated': 'Order Created',
    'orders.paymentDetected': 'Payment Detected',
    'orders.confirming': 'Confirming',
    'orders.inProgress': 'In Progress',
    'orders.pendingConfirmation': 'Pending Confirmation',
    'orders.technicalLogs': 'Technical Logs',
    'orders.downloadFullLog': 'Download Full Log',

    // Withdraw
    'withdraw.title': 'Withdrawals',
    'withdraw.subtitle': 'Manage your payouts and fund withdrawals.',
    'withdraw.availableBalance': 'Available for Withdraw',
    'withdraw.pending': 'Pending Processing',
    'withdraw.processed24h': 'Processed (24h)',
    'withdraw.securityDelay': 'Security Delay',
    'withdraw.recent': 'Recent Withdrawals',
    'withdraw.request': 'Request Withdrawal',
    'withdraw.batch': 'Batch Withdraw',
    'withdraw.history': 'Withdrawal History',
    'withdraw.method': 'Method',
    'withdraw.destination': 'Destination',
    'withdraw.fee': 'Fee',
    'withdraw.sentTo': 'sent to',
    'withdraw.receipt': 'Receipt',
    'withdraw.onExplorer': 'on Explorer',
    'withdraw.transactionHash': 'Transaction Hash',
    'withdraw.networkFee': 'Network Fee',
    'withdraw.confirmations': 'Confirmations',
    'withdraw.newWithdrawal': 'New Withdrawal',
    'withdraw.createSubtitle': 'Request a new fund withdrawal',
    'withdraw.viewingDetails': 'Viewing details for',
    'withdraw.transactionDetails': 'Transaction Details',
    'withdraw.transferDetails': 'Transfer Details',
    'withdraw.enterDetails': 'Enter withdrawal details',
    'withdraw.selectAsset': 'Select Asset',
    'withdraw.available': 'Available',
    'withdraw.destinationAddress': 'Destination Address',
    'withdraw.totalDeduction': 'Total Deduction',
    'withdraw.confirmWithdrawal': 'Confirm Withdrawal',
    'withdraw.securityNotice': 'Security Notice',
    'withdraw.securityText': 'All withdrawals undergo a 24-hour security review before processing. High-value transactions may require additional verification.',
    'withdraw.availableForWithdrawal': 'Available for Withdrawal',
    'withdraw.totalWithdrawn': 'Total Withdrawn',

    // Integration
    'integration.title': 'Integration Center',
    'integration.subtitle': 'Manage API keys, webhooks, and payment tools.',
    'integration.tabs.apiKeys': 'API Keys',
    'integration.tabs.webhooks': 'Webhooks',
    'integration.tabs.buttons': 'Payment Buttons',
    'integration.apiCredentials': 'API Credentials',
    'integration.apiDesc': 'Manage your API keys for backend integration.',
    'integration.clientId': 'Client ID',
    'integration.apiKey': 'API Key',
    'integration.apiKeyWarning': 'Keep this key secret! Do not share it.',
    'integration.resetApiKey': 'Reset API Key',
    'integration.webhookConfig': 'Webhook Configuration',
    'integration.webhookDesc': 'Configure webhook endpoints for real-time notifications.',
    'integration.endpointUrl': 'Endpoint URL',
    'integration.events': 'Events',
    'integration.addEndpoint': 'Add Endpoint',
    'integration.buttonConfig': 'Button Configuration',
    'integration.buttonDesc': 'Generate copy-paste payment buttons for your website.',
    'integration.itemName': 'Item Name',
    'integration.token': 'Token',
    'integration.network': 'Network',
    'integration.generatedCode': 'Generated Code',
    'integration.preview': 'Preview',
    'integration.copyCode': 'Copy Code',
    'integration.payWithCrypto': 'Pay with Crypto',
    'integration.apiDocs': 'API Documentation',
    'integration.apiKeys': 'API Keys',
    'integration.webhooks': 'Webhooks',
    'integration.paymentButtons': 'Payment Buttons',

    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account preferences and configurations.',
    'settings.general': 'General',
    'settings.verification': 'Verification',
    'settings.financial': 'Financial',
    'settings.invoice': 'Invoice',
    'settings.profileInfo': 'Profile Information',
    'settings.profileDesc': 'Update your personal details and timezone.',
    'settings.fullName': 'Full Name',
    'settings.email': 'Email Address',
    'settings.phone': 'Phone Number',
    'settings.timezone': 'Timezone',
    'settings.businessVerification': 'Business Verification',
    'settings.verificationDesc': 'Verify your business to increase limits.',
    'settings.level1Verified': 'Level 1 Verified',
    'settings.dailyLimit': 'Daily Limit',
    'settings.monthlyLimit': 'Monthly Limit',
    'settings.withdrawals': 'Withdrawals',
    'settings.instant': 'Instant',
    'settings.requiresLevel2': 'Requires Level 2',
    'settings.upgradeLevel2': 'Upgrade to Level 2',
    'settings.upgradeDesc': 'Unlock higher limits and advanced features by verifying your business.',
    'settings.startVerification': 'Start Verification',
    'settings.autoSweepConfig': 'Auto-Sweep Configuration',
    'settings.autoSweepDesc': 'Configure automatic fund sweeping rules.',
    'settings.enableAutoSweep': 'Enable Auto-Sweep',
    'settings.enableAutoSweepDesc': 'Automatically sweep funds when threshold is met.',
    'settings.sweepMode': 'Sweep Mode',
    'settings.instantMode': 'Instant (High Gas)',
    'settings.hourlyMode': 'Hourly',
    'settings.nightlyMode': 'Nightly (Low Gas)',
    'settings.nightlyDesc': 'Nightly mode saves up to 90% on gas fees by batching transactions.',
    'settings.minThreshold': 'Minimum Threshold',
    'settings.targetCurrency': 'Target Currency',
    'settings.invoiceEntity': 'Invoice Entity',
    'settings.invoiceEntityDesc': 'Manage your business entity details for invoices.',
    'settings.legalName': 'Legal Business Name',
    'settings.taxId': 'Tax ID / VAT Number',
    'settings.businessAddress': 'Business Address',
    'settings.streetAddress': 'Street Address',
    'settings.city': 'City',
    'settings.postalCode': 'Postal Code',
    'settings.country': 'Country',
    'settings.autoGenInvoice': 'Auto-Generate Invoices',
    'settings.autoGenInvoiceDesc': 'Automatically generate invoices for all new orders.',

    // KYB
    'kyb.title': 'Verify your Business',
    'kyb.subtitle': 'Complete the KYB process to activate your crypto wallet and start accepting payments. Your progress is saved automatically.',
    'kyb.draftSaved': 'Draft saved',
    'kyb.step': 'Step',
    'kyb.of': 'of',
    'kyb.next': 'Next',
    'kyb.review': 'Review',
    'kyb.step1': 'Identity',
    'kyb.step2': 'Location',
    'kyb.step3': 'Documents',
    'kyb.dba': 'Doing Business As (DBA)',
    'kyb.optional': 'Optional',
    'kyb.regNumber': 'Registration Number',
    'kyb.website': 'Company Website',
    'kyb.countryInc': 'Country of Incorporation',
    'kyb.selectCountry': 'Select country...',
    'kyb.state': 'State / Province',
    'kyb.certInc': 'Certificate of Incorporation',
    'kyb.proofAddress': 'Proof of Address',
    'kyb.clickUpload': 'Click to upload',
    'kyb.dragDrop': 'or drag and drop',
    'kyb.saveDraft': 'Save as Draft',
    'kyb.whyNeed': 'Why do we need this?',
    'kyb.whyNeedDesc': 'As a regulated financial institution, we are required to collect and verify information about your business to comply with',
    'kyb.aml': 'Anti-Money Laundering (AML)',
    'kyb.regulations': 'regulations',
    'kyb.docGuidelines': 'Document Guidelines',
    'kyb.guide1': 'Must be issued within last 3 months',
    'kyb.guide2': 'All 4 corners must be visible',
    'kyb.guide3': 'Text must be clearly legible',
    'kyb.guide4': 'No screenshots allowed',
    'kyb.needHelp': 'Need Help?',
    'kyb.contactSupportDesc': 'Our compliance team is available to assist you.',
    'kyb.contactSupport': 'Contact Support',
  },
  zh: {
    // Navigation
    'nav.dashboard': '仪表盘',
    'nav.assets': '资产管理',
    'nav.orders': '订单记录',
    'nav.integration': '集成中心',
    'nav.withdraw': '提现管理',
    'nav.settings': '系统设置',
    'nav.signout': '退出登录',
    'nav.merchantPortal': '商户门户 v2.1',

    // Dashboard
    'dashboard.welcome': '欢迎回来，商户。这是您的财务概览。',
    'dashboard.revenue': '总收入',
    'dashboard.activeOrders': '活跃订单',
    'dashboard.pendingPayouts': '待处理提现',
    'dashboard.accountStatus': '账户状态',
    'dashboard.quickActions': '快捷操作',
    'dashboard.revenueOverview': '收入概览',
    'dashboard.completeProfile': '完善您的资料',
    'dashboard.completeProfileDesc': '添加您的企业实体信息以启用自动发票功能。',
    'dashboard.goToSettings': '前往设置',
    'dashboard.fromLastMonth': '与上月相比',
    'dashboard.sinceLastHour': '过去一小时',
    'dashboard.scheduledTonight': '计划今晚处理',
    'dashboard.transactions': '交易',
    'dashboard.transactionHistory': '交易历史',

    // Actions
    'action.createInvoice': '创建发票',
    'action.withdraw': '提现',
    'action.apiKeys': 'API 密钥',
    'action.settings': '设置',
    'action.copy': '复制',
    'action.copied': '已复制',
    'action.view': '查看',
    'action.download': '下载',
    'action.filter': '筛选',
    'action.export': '导出',
    'action.search': '搜索',
    'action.save': '保存更改',
    'action.cancel': '取消',
    'action.generate': '生成',
    'action.regenerate': '重新生成',
    'action.delete': '删除',
    'action.edit': '编辑',
    'action.verify': '立即认证',
    'action.continue': '继续',

    // Status
    'status.active': '活跃',
    'status.verified': '二级认证通过',
    'status.kybVerified': 'KYB 已认证',
    'status.systemActive': '系统运行中',
    'status.completed': '已完成',
    'status.pending': '待处理',
    'status.processing': '处理中',
    'status.failed': '失败',
    'status.cancelled': '已取消',
    'status.refunded': '已退款',

    // Assets
    'assets.title': '资产管理',
    'assets.subtitle': '监控您的多链余额和归集状态。',
    'assets.totalBalance': '总余额',
    'assets.swept': '已归集 (冷钱包)',
    'assets.unswept': '未归集 (热钱包)',
    'assets.autoSweep': '自动归集',
    'assets.on': '开启',
    'assets.off': '关闭',
    'assets.asset': '资产',
    'assets.chain': '链',
    'assets.balance': '余额',
    'assets.value': '价值 (USD)',
    'assets.status': '状态',
    'assets.action': '操作',
    'assets.sweepNow': '立即归集',

    // Orders
    'orders.title': '订单历史',
    'orders.subtitle': '查看和管理您的交易记录。',
    'orders.orderId': '订单号',
    'orders.customer': '客户',
    'orders.amount': '金额',
    'orders.date': '日期',
    'orders.paymentMethod': '支付方式',
    'orders.invoice': '发票',
    'orders.allStatus': '全部状态',
    'orders.allTypes': '全部类型',
    'orders.type': '类型',
    'orders.payment': '支付',
    'orders.payout': '提现',
    'orders.onExplorer': '在区块浏览器查看',
    'orders.csv': 'CSV',
    'orders.createdOn': '创建于',
    'orders.totalAmount': '总金额',
    'orders.fiatEquivalent': '法币等值',
    'orders.timeRemaining': '剩余时间',
    'orders.paymentDetails': '支付详情',
    'orders.network': '网络',
    'orders.destination': '目标地址',
    'orders.txHash': '交易哈希',
    'orders.blockHeight': '区块高度',
    'orders.confirmations': '确认数',
    'orders.timeline': '支付时间线',
    'orders.orderCreated': '订单创建',
    'orders.paymentDetected': '检测到支付',
    'orders.confirming': '确认中',
    'orders.inProgress': '进行中',
    'orders.pendingConfirmation': '等待确认',
    'orders.technicalLogs': '技术日志',
    'orders.downloadFullLog': '下载完整日志',

    // Withdraw
    'withdraw.title': '提现管理',
    'withdraw.subtitle': '管理您的资金提现和转账。',
    'withdraw.availableBalance': '可提现余额',
    'withdraw.pending': '待处理',
    'withdraw.processed24h': '24小时内已处理',
    'withdraw.securityDelay': '安全延迟',
    'withdraw.recent': '最近提现',
    'withdraw.request': '申请提现',
    'withdraw.batch': '批量提现',
    'withdraw.history': '提现历史',
    'withdraw.method': '方式',
    'withdraw.destination': '目标地址',
    'withdraw.fee': '手续费',
    'withdraw.sentTo': '发送至',
    'withdraw.receipt': '收据',
    'withdraw.onExplorer': '在区块浏览器查看',
    'withdraw.transactionHash': '交易哈希',
    'withdraw.networkFee': '网络费用',
    'withdraw.confirmations': '确认数',
    'withdraw.newWithdrawal': '新建提现',
    'withdraw.createSubtitle': '申请新的资金提现',
    'withdraw.viewingDetails': '查看详情',
    'withdraw.transactionDetails': '交易详情',
    'withdraw.transferDetails': '转账详情',
    'withdraw.enterDetails': '输入提现详情',
    'withdraw.selectAsset': '选择资产',
    'withdraw.available': '可用',
    'withdraw.destinationAddress': '目标地址',
    'withdraw.totalDeduction': '总扣除',
    'withdraw.confirmWithdrawal': '确认提现',
    'withdraw.securityNotice': '安全提示',
    'withdraw.securityText': '所有提现申请将经过24小时安全审查后处理。大额交易可能需要额外验证。',
    'withdraw.availableForWithdrawal': '可提现',
    'withdraw.totalWithdrawn': '已提现总额',

    // Integration
    'integration.title': '集成中心',
    'integration.subtitle': '管理 API 密钥、Webhook 和支付工具。',
    'integration.tabs.apiKeys': 'API 密钥',
    'integration.tabs.webhooks': 'Webhooks',
    'integration.tabs.buttons': '支付按钮',
    'integration.apiCredentials': 'API 凭证',
    'integration.apiDesc': '管理用于后端集成的 API 密钥。',
    'integration.clientId': '客户端 ID',
    'integration.apiKey': 'API 密钥',
    'integration.apiKeyWarning': '请妥善保管此密钥！切勿泄露。',
    'integration.resetApiKey': '重置 API 密钥',
    'integration.webhookConfig': 'Webhook 配置',
    'integration.webhookDesc': '配置用于实时通知的 Webhook 端点。',
    'integration.endpointUrl': '端点 URL',
    'integration.events': '事件',
    'integration.addEndpoint': '添加端点',
    'integration.buttonConfig': '按钮配置',
    'integration.buttonDesc': '生成可直接复制粘贴到您网站的支付按钮代码。',
    'integration.itemName': '商品名称',
    'integration.token': '代币',
    'integration.network': '网络',
    'integration.generatedCode': '生成代码',
    'integration.preview': '预览',
    'integration.copyCode': '复制代码',
    'integration.payWithCrypto': '使用加密货币支付',
    'integration.apiDocs': 'API 文档',
    'integration.apiKeys': 'API 密钥',
    'integration.webhooks': 'Webhooks',
    'integration.paymentButtons': '支付按钮',

    // Settings
    'settings.title': '系统设置',
    'settings.subtitle': '管理您的账户偏好和配置。',
    'settings.general': '常规',
    'settings.verification': '认证',
    'settings.financial': '财务',
    'settings.invoice': '发票',
    'settings.profileInfo': '个人信息',
    'settings.profileDesc': '更新您的个人详细信息和时区。',
    'settings.fullName': '全名',
    'settings.email': '电子邮件',
    'settings.phone': '电话号码',
    'settings.timezone': '时区',
    'settings.businessVerification': '企业认证',
    'settings.verificationDesc': '验证您的企业以提高限额。',
    'settings.level1Verified': '一级认证通过',
    'settings.dailyLimit': '每日限额',
    'settings.monthlyLimit': '每月限额',
    'settings.withdrawals': '提现',
    'settings.instant': '即时',
    'settings.requiresLevel2': '需要二级认证',
    'settings.upgradeLevel2': '升级到二级认证',
    'settings.upgradeDesc': '通过验证您的企业来解锁更高限额和高级功能。',
    'settings.startVerification': '开始认证',
    'settings.autoSweepConfig': '自动归集配置',
    'settings.autoSweepDesc': '配置自动资金归集规则。',
    'settings.enableAutoSweep': '启用自动归集',
    'settings.enableAutoSweepDesc': '当达到阈值时自动归集资金。',
    'settings.sweepMode': '归集模式',
    'settings.instantMode': '即时 (高 Gas)',
    'settings.hourlyMode': '每小时',
    'settings.nightlyMode': '夜间 (低 Gas)',
    'settings.nightlyDesc': '夜间模式通过批量处理交易可节省高达 90% 的 Gas 费。',
    'settings.minThreshold': '最低阈值',
    'settings.targetCurrency': '目标货币',
    'settings.invoiceEntity': '发票实体',
    'settings.invoiceEntityDesc': '管理发票上的企业实体详细信息。',
    'settings.legalName': '法定企业名称',
    'settings.taxId': '税号 / VAT',
    'settings.businessAddress': '企业地址',
    'settings.streetAddress': '街道地址',
    'settings.city': '城市',
    'settings.postalCode': '邮政编码',
    'settings.country': '国家',
    'settings.autoGenInvoice': '自动生成发票',
    'settings.autoGenInvoiceDesc': '为所有新订单自动生成发票。',

    // KYB
    'kyb.title': '验证您的企业',
    'kyb.subtitle': '完成 KYB 流程以激活您的加密钱包并开始接受付款。您的进度会自动保存。',
    'kyb.draftSaved': '草稿已保存',
    'kyb.step': '步骤',
    'kyb.of': '/',
    'kyb.next': '下一步',
    'kyb.review': '审核',
    'kyb.step1': '身份',
    'kyb.step2': '位置',
    'kyb.step3': '文件',
    'kyb.dba': '经营名称 (DBA)',
    'kyb.optional': '可选',
    'kyb.regNumber': '注册号',
    'kyb.website': '公司网站',
    'kyb.countryInc': '注册国家',
    'kyb.selectCountry': '选择国家...',
    'kyb.state': '州 / 省',
    'kyb.certInc': '注册证书',
    'kyb.proofAddress': '地址证明',
    'kyb.clickUpload': '点击上传',
    'kyb.dragDrop': '或拖放文件',
    'kyb.saveDraft': '保存草稿',
    'kyb.whyNeed': '为什么需要这个？',
    'kyb.whyNeedDesc': '作为受监管的金融机构，我们需要收集和验证您的企业信息以遵守',
    'kyb.aml': '反洗钱 (AML)',
    'kyb.regulations': '法规',
    'kyb.docGuidelines': '文件指南',
    'kyb.guide1': '必须在过去 3 个月内签发',
    'kyb.guide2': '所有 4 个角必须可见',
    'kyb.guide3': '文字必须清晰可辨',
    'kyb.guide4': '不允许截图',
    'kyb.needHelp': '需要帮助？',
    'kyb.contactSupportDesc': '我们的合规团队随时为您提供帮助。',
    'kyb.contactSupport': '联系支持',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
